version: "{build}"
environment:
  global:
    E2D_WITHOUT_AUDIO: true
    E2D_WITHOUT_GRAPHICS: true
image:
  - Visual Studio 2017
  - Visual Studio 2019
platform:
  - Win32
  - x64
build_script:
  - git submodule update --init --recursive
  - scripts\build_release.bat
test: off
